# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "586d233e338321baf7feb44e6d0271ab"
name = "qr-code-creator"
handle = "qr-code-creator-8"
application_url = "https://example.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
